### ISSUE TITLE
feat: remove seurat convertability check

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#1112]
## Motivation

Seurat conversion will not longer be supporting going forward. This mean checks related to Seurat convertibility no longer need to be done.

## Definition of Done
- Remove all code and tests related to Seurat convertibility.

## Tasks

- [x] remove the flag [is_seurat_convertible](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/validate.py#L57-L57)
- [x] remove the function [_validate_seurat_convertibility](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/validate.py#L929-L929)
- [x] remove tests related to seurat in [test_validate.py](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/tests/test_validate.py#L300-L300)
- [x] remove seurat references from [schema_definition.yaml](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/cellxgene_schema/schema_definitions/schema_definition.yaml#L6-L6)
