### ISSUE TITLE
move stateful checks (e.g. is_visium, is_single) higher up in the validator to avoid potential state-related issues

### ISSUE THREAD

**Issue by ejmolinelli** [chanzuckerberg/single-cell-curation#1125]
## Motivation
The `Validator` object is stateful, and there are various points in the life of a validator object when a state might be set during validation. The states should be defined as early as possible and in a single place to avoid potential complications.

An example pointed out [here](https://github.com/chanzuckerberg/single-cell-curation/pull/1124/files/00afc7bb5353344162c4b1786729a467976834ea#r1852964151)

## Definition of Done
the Validator state property setter functions are called once and only once (not counting after `Validator.reset()`.

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ] cull state proeprty setters into a new or existing function
- [ ] call this function early in Validator life cycle
- [ ] remove all other property setter calls.
- [ ] state should be recomputed after `adata` is reassigned.

### Extra Credit
- [ ] Extend more formal object properties with `@property` and `@property.setter` decorators (already used for Validator.adata)
