### ISSUE TITLE
Support adding labels to larger datasets by reducing memory cost

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/single-cell-curation#416]
## Motivation

In order to support larger h5ads we need to reduce the amount of memory required. The way AnnDataLabelAppender is currently written, it triples the amount of memory required. The explosion of memory required can be avoided if we eliminated making a copying of the anndata. 

## Definition of Done

Avoid make a copy of the original dataset in memory to process it with the AnnDataLabelAppender.

### Suggestion

Remove the `copy` and `to_memory` of the annData when initializing AnnDataLabelAppender. The validator which is passed in as a parameter to this class already has the anndata opened and loaded as read only. That means it will be read and modified without need to make a full copy. The required parts will be loaded as needed and written to a new file, leaving the original file intact. 
   
https://github.com/chanzuckerberg/single-cell-curation/blob/79a78b41414441d6f79ecf57baa57e3cea0c5eb3/cellxgene_schema_cli/cellxgene_schema/write_labels.py#L33-L36
changed to 
```
self.adata = validator.adata
```

This change should not affect the contents of the new file produced. 

## Tasks
- [ ] remove the copy of anndata into memory
- [ ] verify that both the original h5ad remains unchanged.
- [ ] verify that the labeled h5ad produced is the same file as before the changes were implemented. No regression.

## Notes
- comparing the hash of the h5ads is enough to ensure they are they same.
